[tool.poetry]
name = "learning-pytest"
version = "0.1.0"
description = ""
authors = [
    "Andrés Ramirez Miori <andres.ramirez.miori@gmail.com>",
    "Mariano Bianchi <marianobianchi08@gmail.com>"
    ]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
